---
- hosts: crow
  become: yes

  tasks:
    # custom cogs
    - synchronize:
        src: ../cogs
        dest: /opt/crow/
    
    # system account
    - user:
        name: crow
        group: users
        system: yes
        create_home: no
        password: "!"
      register: crow_user

    # packages
    - apt:
        name:
          - python3
          - python3-dev
          - python3-venv
          - python3-pip
          - git
          - openjdk-11-jre-headless
          - build-essential
          - nano
          - rsync

    # bot installation
    - file:
        path: /opt/crow
        state: directory
    - pip:
        name:
          - pip
          - setuptools
          - wheel
          - Red-DiscordBot
          - Pillow
        virtualenv: /opt/crow
        virtualenv_command: /usr/bin/python3 -m venv
    
    # bot config
    - file:
        path: /usr/local/share/Red-DiscordBot
        state: directory
        owner: crow
    - copy:
        src: red.service
        dest: /etc/systemd/system/red@.service
    - systemd:
        name: red@crow
        state: started
        enabled: yes
        daemon_reload: yes
